allprojects {
    apply plugin: 'eclipse'

    version = '1.0'
    ext {
        appName = 'NotTrollGame'
        gdxVersion = '1.14.2'
    }

    repositories {
        mavenLocal()
        mavenCentral()
        google()
        maven { url 'https://s01.oss.sonatype.org' }
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
    }
}

configure(subprojects) {
    apply plugin: 'java-library'
    sourceCompatibility = 17
    targetCompatibility = 17
}
